# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.size_chooser = QtWidgets.QComboBox(self.centralwidget)
        self.size_chooser.setGeometry(QtCore.QRect(130, 340, 131, 41))
        self.size_chooser.setObjectName("size_chooser")
        self.size_chooser.addItem("")
        self.size_chooser.addItem("")
        self.size_chooser.addItem("")
        self.final_resize_button = QtWidgets.QPushButton(self.centralwidget)
        self.final_resize_button.setGeometry(QtCore.QRect(280, 400, 100, 32))
        self.final_resize_button.setObjectName("final_resize_button")
        self.dragndropbox = QtWidgets.QGraphicsView(self.centralwidget)
        self.dragndropbox.setGeometry(QtCore.QRect(10, 10, 381, 321))
        self.dragndropbox.setObjectName("dragndropbox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.size_chooser.setItemText(0, _translate("MainWindow", "688x459"))
        self.size_chooser.setItemText(1, _translate("MainWindow", "320x320"))
        self.size_chooser.setItemText(2, _translate("MainWindow", "both"))
        self.final_resize_button.setText(_translate("MainWindow", "Resize!"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
